### ISSUE TITLE
Exception raised: 

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#300] opened 2018-09-27 02:05 UTC
An exception was encountered in [this session](https://transfer.sh/6rI42/session.smh) using version 12eec10 on Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]:

````python
Traceback (most recent call last):

  File "/Users/madelyncain/smhr-2/smhr/smh/gui/chemical_abundances.py", line 945, in selected_model_changed
    self.update_spectrum_figure(True)

  File "/Users/madelyncain/smhr-2/smhr/smh/gui/chemical_abundances.py", line 980, in update_spectrum_figure
    label_rv=label_rv)

  File "/Users/madelyncain/smhr-2/smhr/smh/gui/base.py", line 294, in update_spectrum_figure
    success = self._plot_model()

  File "/Users/madelyncain/smhr-2/smhr/smh/gui/base.py", line 623, in _plot_model
    assert len(meta["model_x"]) == len(meta["residual"])

AssertionError
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/LKr4l/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment] 2018-09-27 02:07
This is caused by a mismatch between turning on the "full_synth_resolution"
parameter (so it keeps/plots the full native resolution of the MOOG
synthesis) and a previously saved file. If you rerun a fit it should work.

**Comment by maddiecain** [comment] 2018-09-27 02:08
Rerun a fit how? I tried to refit, but it kept bugging out and SMH crashed

**Comment by alexji** [comment] 2018-09-27 02:12
Try setting in the .smh_session.defaults file either:

full_synth_resolution: 1

or

full_synth_resolution: 0

And see if it works either way?

**Comment by alexji** [comment] 2018-10-24 07:29
Closing because no comment, assuming it's resolved

**Closed by alexji** 2018-10-24 07:29 UTC
