### ISSUE TITLE
Exception raised: operator not implemented.

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#314] opened 2019-05-01 01:37 UTC
An exception was encountered in [this session](https://transfer.sh/r3kTq/session.smh) using version 12eec10 on Python 2.7.15 |Anaconda, Inc.| (default, Oct 23 2018, 13:35:16) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]:

````python
Traceback (most recent call last):

  File "/Users/madelyncain/smhr-2/smhr/smh/gui/stellar_parameters.py", line 913, in selected_model_changed
    self.update_selected_points()

  File "/Users/madelyncain/smhr-2/smhr/smh/gui/stellar_parameters.py", line 859, in update_selected_points
    self.table_view.selectionModel().selectedIndexes()]))

  File "/Users/madelyncain/anaconda2/lib/python2.7/site-packages/numpy/lib/arraysetops.py", line 266, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)

  File "/Users/madelyncain/anaconda2/lib/python2.7/site-packages/numpy/lib/arraysetops.py", line 314, in _unique1d
    ar.sort()

NotImplementedError: operator not implemented.
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/15FEcw/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment] 2019-05-01 01:44
Duplicate of #311

**Closed** 2019-05-01 01:44 UTC

**Comment by maddiecain** [comment] 2019-05-01 01:45
is there a quick way to see the versions of all the packages we need?

**Comment by alexji** [comment] 2019-05-01 01:47
They should all be in the installation instructions on the SMHR page.
However I have not yet added this one because it broke relatively recently.
Adding now.
