### ISSUE TITLE
Exception raised: [Errno 2] No such file or directory: u'/Users/maudegull/.smh/tmpd3uM5h/abfind.sum.out'

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#294] opened 2018-07-19 17:25 UTC
An exception was encountered using version e94df1f* on Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]:

````python
Traceback (most recent call last):

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/gui/stellar_parameters.py", line 664, in measure_abundances
    filtering=filtering)

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/session.py", line 879, in stellar_parameter_state
    self.stellar_photosphere, transitions[finite], twd=self.twd)

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/radiative_transfer/moog/cog.py", line 114, in abundance_cog
    transitions_array, linear_fits = _parse_abfind_summary(kwds["summary_out"])

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/radiative_transfer/moog/cog.py", line 172, in _parse_abfind_summary
    with open(summary_out_path, "r") as fp:

IOError: [Errno 2] No such file or directory: u'/Users/maudegull/.smh/tmpd3uM5h/abfind.sum.out'
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/KbA1F/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by mgull19** [comment] 2018-07-24 02:13
Any chance this got resolved???

**Comment by alexji** [comment] 2018-07-25 17:53
Duplicate of #295

**Closed by alexji** 2018-07-25 17:53 UTC
