### ISSUE TITLE
Exception raised: cannot fit 'long' into an index-sized integer

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#275] opened 2018-01-14 00:27 UTC
An exception was encountered using version fd39f2f on Python 2.7.6 | 32-bit | (default, Sep 15 2014, 17:36:57) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]:

````python
Traceback (most recent call last):

  File "/Users/madelyncain/smhr/smh/gui/chemical_abundances.py", line 839, in fit_one
    res = spectral_model.fit()

  File "/Users/madelyncain/smhr/smh/spectral_models/synthesis.py", line 407, in fit
    sigma=yerr, p0=p0, absolute_sigma=absolute_sigma)

  File "/Users/madelyncain/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 555, in curve_fit
    res = leastsq(func, p0, args=args, full_output=1, **kw)

  File "/Users/madelyncain/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 379, in leastsq
    gtol, maxfev, epsfcn, factor, diag)

  File "/Users/madelyncain/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 449, in _weighted_general_function
    return weights * (function(xdata, *params) - ydata)

  File "/Users/madelyncain/smhr/smh/spectral_models/synthesis.py", line 404, in objective_function
    x, synth_dispersion, intensities, *parameters)

  File "/Users/madelyncain/smhr/smh/spectral_models/synthesis.py", line 688, in _nuisance_methods
    model = gaussian_filter(model, kernel)

  File "/Users/madelyncain/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/scipy/ndimage/filters.py", line 305, in gaussian_filter
    mode, cval, truncate)

  File "/Users/madelyncain/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/scipy/ndimage/filters.py", line 213, in gaussian_filter1d
    weights = [0.0] * (2 * lw + 1)

OverflowError: cannot fit 'long' into an index-sized integer
````

**Additional details on how this exception occurred**:

**Comment by alexji** [comment] 2018-02-12 23:15
Can you send me the SMHR file that does this? I've never run into such an issue before.

**Comment by alexji** [comment] 2019-01-24 06:50
Closing since issue was not reproduced

**Closed by alexji** 2019-01-24 06:50 UTC
